# Generated by Django 3.1.5 on 2021-01-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='contribution',
            field=models.CharField(default='Contributor', max_length=100, verbose_name='Please enter your contributions.'),
        ),
    ]
