# Generated by Django 3.1.5 on 2021-01-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_team_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='Team_profile_media'),
        ),
    ]
