# Generated by Django 3.1.5 on 2021-01-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_team_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='codeaurahelpdesk@gmail.com', max_length=254, verbose_name='Email')),
            ],
        ),
    ]
