# Generated by Django 3.1.5 on 2021-01-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210125_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='password',
            field=models.CharField(default=12345, max_length=100),
            preserve_default=False,
        ),
    ]
