# Generated by Django 3.1.5 on 2021-01-25 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_signup_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignUp',
            new_name='User',
        ),
    ]
